
rel:
	vcbuild -r se_core Release
	vcbuild -r se_client Release
	vcbuild -r se_ogre Release
	vcbuild -r ui Release
	vcbuild -r simple Release

dbg:
	vcbuild -r se_core Debug
	vcbuild -r se_client Debug
	vcbuild -r se_ogre Debug
	vcbuild -r ui Debug
	vcbuild -r simple Debug
