
rel:
	vcbuild se_core Release
	vcbuild se_client Release
	vcbuild se_ogre Release
	vcbuild logic Release
	vcbuild ui Release
	vcbuild simple Release

dbg:
	vcbuild se_core Debug
	vcbuild se_client Debug
	vcbuild se_ogre Debug
	vcbuild logic Debug
	vcbuild ui Debug
	vcbuild simple Debug

clean:
	vcbuild -c se_core Release
	vcbuild -c se_client Release
	vcbuild -c se_ogre Release
	vcbuild -c logic Release
	vcbuild -c ui Release
	vcbuild -c simple Release

