######################################################################
# Automatically generated by qmake (2.01a) to. okt. 26 11:07:27 2006
######################################################################

TEMPLATE = app
TARGET = tmp
DEPENDPATH += /home/rune/svn/sf/tools/qt/assetEditor/src \
              /home/rune/svn/sf/tools/qt/assetEditor/src/io \
              /home/rune/svn/sf/tools/qt/assetEditor/src/schema \
              /home/rune/svn/sf/tools/qt/assetEditor/src/view
INCLUDEPATH += . \
               /home/rune/svn/sf/tools/qt/assetEditor/src/view \
               /home/rune/svn/sf/tools/qt/assetEditor/src/io \
               /home/rune/svn/sf/tools/qt/assetEditor/src/schema

# Input
HEADERS += /home/rune/svn/sf/tools/qt/assetEditor/src/io/AeO3dThingParserModule.hpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/schema/AssetEditorSchema.hpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/assetEditor.h \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/enums.hpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/ExController.hpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/OgreView.hpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/ViewController.hpp
FORMS += /home/rune/svn/sf/tools/qt/assetEditor/src/view/assetEditor.ui
SOURCES += /home/rune/svn/sf/tools/qt/assetEditor/src/main.cpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/io/AeO3dThingParserModule.cpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/schema/AssetEditorSchema.cpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/ExController.cpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/OgreView.cpp \
           /home/rune/svn/sf/tools/qt/assetEditor/src/view/ViewController.cpp
