######################################################################
# Automatically generated by qmake (2.01a) lø 21. okt 13:44:43 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += assetEditor.ui
SOURCES += main.cpp
