######################################################################
# Automatically generated by qmake (2.01a) ti. okt. 24 19:58:27 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += assetEditor.h enums.hpp ExController.hpp ViewController.hpp
FORMS += assetEditor.ui
SOURCES += ExController.cpp main.cpp ViewController.cpp
